### ISSUE TITLE
Keymappings not working

### ISSUE THREAD

**Issue by SamuelGogarty** [vapula87/Keyboarding-Re-Master#2]
Hello, I am trying to configure my tartarus V2, however when i make a new keybinding, then open a terminal to test it, it remains unchanged.

How does the "app/game" profile selection work? will this cause my mapping to only work in that selected game? if so how do I point keyboarding master to the game? I only get an option for a "name" of the game where it seems to just be an empty text field.
Thanks

**Comment by mhackett909** [comment]
Hello there!

One reason the keybindings may not work is because of permissions. Please
see the README if you need help changing them or if you need more general
information.

Once your Tartarus V2 has been added to the device list and is showing as
"Connected," you must set up a new profile for the device in the
configuration menu. The profiles feature allows you to have different key
mappings for different apps and games, but you don't have to do that. Only
one profile is required, and you can name it whatever you want. You can
pick between "App" or "Game" but that is just for your own reference and
does not affect the program. You can use the "Set Profile" button to choose
a different profile (different mappings) for a device.

Once you have successfully created a profile, the configuration menu allows
you to modify individual bindings by clicking the purple dots on the
picture of the device, and it will tell you what the current binding is.
Note that "Display Keymap" appears to have malfunctioned and I will update
the project later. I haven't touched this since 2020, sorry.

I just did some tests here (Ubuntu 20.04) and the bindings are working for
me in the terminal. Verify that your device is showing as "Connected", that
a profile has been selected, and the checkbox is "Enabled."

Let me know if you have any further issues! I hope you get it working!

-Michael

**Comment by SamuelGogarty** [comment]
Hey thanks for answering back so quickly, 
I went to test it to provide more information to help debug the issue.. but now all of a sudden its working as intended, not sure why but, thats great. Thanks!

**Comment by SamuelGogarty** [comment]
For some very odd reason, keymapping has once again resumed to not working, I have my first key set to esc, i load keyboarding master up, and it only prints "1" when i press the button.

The tartarus is seen as connected, and its enabled.

Here is some output when i start up the program, i am not sure what other information I can provide.

`[kaiser@Tsar Keyboarding-Re-Master-0.5.2-stable]$ sudo ./gradlew run

> Configure project :
Project : => no module-info.java found

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :configJavafxRun

> Task :run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/root/.gradle/caches/modules-2/files-2.1/com.thoughtworks.xstream/xstream/1.4.12/a668a33eb8d7c3ac728a3823cf4339ff762c75ca/xstream-1.4.12.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SystemTray is not supported
Update check failed: Could not retrieve latest version.

(java:24280): Gdk-WARNING **: 11:54:35.453: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`


If you have any suspicions as to what im doing wrong, or know of more information I can provide, please let me know, thank you.

**Comment by SamuelGogarty** [comment]
Also worth mentioning that the "keys repeat" toggle option *does* work, so it seems keyboarding remaster is not absolutely 0 communication with my device

**Comment by SamuelGogarty** [comment]
once again it has started working again... 
things to be a bit inconsistent, I have no clue.

**Comment by mhackett909** [comment]
That is really odd! What is your OS? Are there any error messages in the
terminal when it fails?

**Comment by SamuelGogarty** [comment]
my terminal output when running it: 
[kaiser@Tsar Keyboarding-Re-Master-0.5.2-stable]$ sudo ./gradlew run

> Configure project :
Project : => no module-info.java found

> Task :compileJava UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :configJavafxRun

> Task :run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/root/.gradle/caches/modules-2/files-2.1/com.thoughtworks.xstream/xstream/1.4.12/a668a33eb8d7c3ac728a3823cf4339ff762c75ca/xstream-1.4.12.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Update check failed: Could not retrieve latest version.

`(java:10999): Gdk-WARNING **: 16:34:52.488: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.`


I am running Void Linux.

it seems it will work, then the next day, even though i dont close keyboarding master, the keymappings stop working, i can work around this by rebooting... but this is very undesirable.

**Comment by SamuelGogarty** [comment]
so it seems the issue occurs when i start a openrazer frontend utility(razergenie in this case), which invokes the openrazer-daemon, which stops the keymapping from working. this can be worked around by killing the openrazer-daemon process and restarting keyboarding-remaster(maybe not needed).
